// src/lib/components/Navigation.svelte
<script lang="ts">
	import Search from '$lib/components/Search.svelte';
</script>

<nav>
	<a href="/">Etusivu</a>
	<a href="/categories">Kategoriat</a>
	<a href="/tags">Tagit</a>
	<a href="https://arkisto.klaanon.fi/soundtracks/">Soundtrackit</a>
	<Search />
</nav>

<style lang="scss">
	nav {
		height: 3em;
		padding: 0;
		width: 101%;
		margin: 0 0 0 -0.5%;
		line-height: 2.5em;
		display: flex;
		justify-content: center;
		flex-wrap: wrap;
		a {
			margin-left: 0.5rem;
			margin-right: 0.5rem;
		}
	}
</style>

// src/components/navigation.tsx
import { Link } from "gatsby";
import React from "react";
import Search from "./search";
const searchIndices = [{ name: `Posts`, title: `Posts` }];

const Navigation = () => {
  return (
    <nav className="navigation">
      <div className="navigationItem">
        <Link to="/">Etusivu</Link>
      </div>
      <div className="navigationItem">
        <a href="https://arkisto.klaanon.fi/soundtracks/">Soundtracks</a>
      </div>
      <div className="navigationItem">
        <Link to="/tags">Tagit</Link>
      </div>
      <div className="navigationItem">
        <Search indices={searchIndices} />
      </div>
    </nav>
  );
};

export default Navigation;
